export const NUTRIENTS = ['N', 'P', 'K'] as const;
export type Nutrient = typeof NUTRIENTS[number];
export type NutrientTotals = Record<Nutrient, number>;
export const emptyTotals = (): NutrientTotals => ({ N: 0, P: 0, K: 0 });
export const PLANT_TARGET = 12;
export const NUTRIENT_INFO = {
  N: { name: 'Nitrogen', color: '#d4ff70', role: 'Builds proteins and chlorophyll.', detail: 'Plants use nitrogen to build proteins and the chlorophyll involved in photosynthesis. Greener leaves here illustrate one role; nutrient effects overlap.', source: 'https://extension.umd.edu/sites/extension.umd.edu/files/2021-04/IPNI_FCHH%20Vol.3_RR.pdf' },
  P: { name: 'Phosphorus', color: '#72eadc', role: 'Part of DNA and ATP, the energy-transfer molecule.', detail: 'Phosphorus is part of DNA, RNA and ATP. Plants take it up as phosphate. Our root-growth animation illustrates plant development, not a function exclusive to phosphorus.', source: 'https://swroc.cfans.umn.edu/research/soil-water/phosphorus-cycle' },
  K: { name: 'Potassium', color: '#b78aff', role: 'Helps regulate water and activate enzymes.', detail: 'Potassium helps regulate the opening and closing of leaf pores and activates enzymes. The upright plant illustrates water regulation; potassium is not a substitute for watering.', source: 'https://extension.umd.edu/sites/extension.umd.edu/files/2021-04/organic%20N%2C%20P%20%26%20K_ipni.pdf' },
} as const;
// Three survey samples unlock the N/P/K areas; seven discovery samples teach more
// of the community and pay a publication bonus. Ordered by depth, shallow to deep.
export const SURVEY_IDS = ['root-partner', 'phosphorus-helper', 'root-risk'] as const;
export const SAMPLE_IDS = ['root-partner', 'root-guard', 'nitrogen-catcher', 'antibiotic-maker', 'phosphorus-helper', 'root-extender', 'fungus-fighter', 'ammonia-oxidizer', 'root-risk', 'deep-archaeon'] as const;
export type SampleId = typeof SAMPLE_IDS[number];
export const DISCOVERY_BONUS = 25;
export const MICROBES: Record<SampleId, { name: string; role: string; short: string; detail: string; condition: string; nutrient: Nutrient | null; source: string }> = {
  'root-partner': { name: 'Rhizobium leguminosarum', role: 'Root partner', short: 'Compatible strains partner with peas in root nodules to fix nitrogen.', detail: 'In a compatible pea–bacterium partnership, bacteria in root nodules convert nitrogen gas to forms the plant can use. Finding related DNA is a clue, not proof of active nitrogen fixation. The paired soil survey maps existing N deposits; the DNA match does not measure nitrogen levels.', condition: 'Supportive root conditions', nutrient: 'N', source: 'https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2017.02249/full' },
  'root-guard': { name: 'Pseudomonas fluorescens', role: 'Root guard', short: 'Some strains colonize roots and suppress soil pathogens.', detail: 'Certain strains coat plant roots and produce compounds that hold back fungal pathogens, a natural form of biocontrol. This ability varies by strain and environment; a DNA match shows presence, not protection.', condition: 'Rhizosphere resident', nutrient: null, source: 'https://en.wikipedia.org/wiki/Pseudomonas_fluorescens' },
  'nitrogen-catcher': { name: 'Azotobacter vinelandii', role: 'Free-living nitrogen fixer', short: 'Fixes nitrogen gas without a plant partner, at a high energy cost.', detail: 'Unlike Rhizobium, Azotobacter fixes nitrogen while living freely in soil. Fixation is energy-hungry, so it depends on rich organic matter. A DNA match does not measure how much nitrogen is actually being fixed.', condition: 'Organic-rich topsoil', nutrient: null, source: 'https://en.wikipedia.org/wiki/Azotobacter_vinelandii' },
  'antibiotic-maker': { name: 'Streptomyces griseus', role: 'Antibiotic maker', short: 'Soil decomposer whose relatives gave us streptomycin — and the smell of earth.', detail: 'Streptomyces bacteria decompose tough plant material and produce many antibiotics, including streptomycin, the first cure for tuberculosis. Their geosmin is the earthy smell after rain. A DNA match shows presence, not antibiotic production.', condition: 'Decomposing organic matter', nutrient: null, source: 'https://en.wikipedia.org/wiki/Streptomyces_griseus' },
  'phosphorus-helper': { name: 'Bacillus subtilis', role: 'Phosphorus helper', short: 'Some strains help release phosphorus into forms plants can take up.', detail: 'Experiments with particular strains show increased phosphorus availability and plant uptake. This ability varies by strain and environment: a species match alone does not establish function. The paired soil survey maps existing P deposits; the DNA match does not measure phosphorus levels.', condition: 'Supportive nutrient conditions', nutrient: 'P', source: 'https://onlinelibrary.wiley.com/doi/full/10.1111/ppl.14338' },
  'root-extender': { name: 'Rhizophagus irregularis', role: 'Root extender', short: 'A mycorrhizal fungus whose threads extend roots toward phosphorus and water.', detail: 'Arbuscular mycorrhizal fungi grow into root cells and trade soil phosphorus and water for plant sugars. Most land plants form such partnerships. A DNA match shows the fungus is present, not that a partnership is active.', condition: 'Root partnership candidate', nutrient: null, source: 'https://en.wikipedia.org/wiki/Rhizophagus_irregularis' },
  'fungus-fighter': { name: 'Trichoderma harzianum', role: 'Fungus fighter', short: 'A fungus used as biocontrol against root diseases.', detail: 'Trichoderma species parasitize other fungi and compete for space on roots, and some strains are sold as biological crop protection. Effects depend on strain and conditions; a DNA match is not a treatment.', condition: 'Competing fungal community', nutrient: null, source: 'https://en.wikipedia.org/wiki/Trichoderma_harzianum' },
  'ammonia-oxidizer': { name: 'Nitrosomonas europaea', role: 'Nitrogen transformer', short: 'Turns ammonia into nitrite, the first step of nitrification.', detail: 'Nitrosomonas gains energy by oxidizing ammonia to nitrite; other microbes then make nitrate that plants absorb. This chain, nitrification, links decomposition to plant nutrition. A DNA match does not measure the rate.', condition: 'Ammonia available', nutrient: null, source: 'https://en.wikipedia.org/wiki/Nitrosomonas_europaea' },
  'root-risk': { name: 'Fusarium oxysporum species complex', role: 'Potential plant pathogen', short: 'Some strains cause root disease or wilt; others do not.', detail: 'This is a fungus, not a bacterium. The complex includes pathogenic and nonpathogenic strains, and its resting spores persist deep in soil for years. A DNA match flags a reason to investigate, not a diagnosis. The marked route avoids gameplay hazards; it does not cure disease.', condition: 'Dormant spores detected · investigate disease risk', nutrient: null, source: 'https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2021.737820/full' },
  'deep-archaeon': { name: 'Nitrososphaera viennensis', role: 'Deep archaeon', short: 'An ammonia-oxidizing archaeon — a third domain of life, common in soil.', detail: 'Archaea look like bacteria but are a separate domain of life. Ammonia-oxidizing archaea are among the most abundant ammonia oxidizers in many soils, including deeper layers. A DNA match shows presence, not measured activity.', condition: 'Low-organic deep soil', nutrient: null, source: 'https://en.wikipedia.org/wiki/Nitrososphaera' },
};
