import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1 });
const errors = []; page.on('pageerror', e => errors.push(e.message));
const base = process.env.BASE_URL || 'http://localhost:5173';
await mkdir('test-results', { recursive: true });
try {
  await page.goto(base); await page.getByRole('button', { name: 'Begin the adventure' }).waitFor();
  await page.screenshot({ path: 'test-results/title.png', fullPage: true });
  await page.getByRole('button', { name: 'Begin the adventure' }).click();
  await page.getByRole('button', { name: 'Let’s dig' }).click();
  await page.keyboard.down('s'); await page.waitForTimeout(3100); await page.keyboard.up('s');
  assert.equal(await page.locator('#scan').isEnabled(),true); // First movement stops at the sample.
  await page.keyboard.down('s');await page.waitForTimeout(700);await page.keyboard.up('s');
  assert.notEqual(await page.locator('#depth').innerText(), '0 tiles');
  await page.keyboard.press('Escape');
  assert.match(await page.locator('#overlay').innerText(), /little breather/);
  const snapshot = await page.evaluate(() => JSON.parse(localStorage.getItem('kreatbio.microload.save')));
  await page.waitForTimeout(200); await page.reload();
  await page.getByRole('button', { name: 'Continue culture' }).waitFor();
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('kreatbio.microload.save'))), snapshot);
  await page.getByRole('button', { name: 'Continue culture' }).click();
  await page.keyboard.press('m'); assert.match(await page.locator('#mute').innerText(), /OFF/);
  await page.keyboard.press('m'); assert.match(await page.locator('#mute').innerText(), /ON/);
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await page.getByRole('button', { name: 'Resume exploration' }).waitFor();
  await page.getByRole('button', { name: 'Resume exploration' }).click();
  await page.keyboard.down('w'); await page.waitForTimeout(1800); await page.keyboard.up('w');
  await page.getByRole('button', { name: /Upgrade/ }).click();
  assert.equal(await page.locator('.upgrade').count(), 4);
  await page.screenshot({ path: 'test-results/shop.png', fullPage: true });
  await page.getByRole('button', { name: 'Back to exploration' }).click();
  await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'Start a new culture' }).click();
  await page.getByRole('button', { name: 'Keep my culture' }).click();
  assert.match(await page.locator('#overlay').innerText(), /little breather/);
  await page.getByRole('button', { name: 'Start a new culture' }).click(); await page.getByRole('button', { name: 'Replace save & start new' }).click();
  await page.getByRole('button', { name: 'Let’s dig' }).click();
  assert.equal(await page.locator('#depth').innerText(), '0 tiles');
  await page.screenshot({ path: 'test-results/gameplay.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.addInitScript(() => localStorage.setItem('kreatbio.microload.save', '{bad'));
  await page.reload(); await page.getByRole('button', { name: 'Begin the adventure' }).waitFor();
  assert.match(await page.locator('#overlay').innerText(), /damaged|could not be read/);
  assert.deepEqual(errors, []);
  console.log('Browser smoke tests passed: start, movement, save/reload, mute, focus pause, shop, reset, responsive layout, invalid save.');
} finally { await browser.close(); }
