import { chromium } from 'playwright';
import { build } from 'esbuild';
import assert from 'node:assert/strict';
const bundled = await build({entryPoints:['src/simulation.ts'],bundle:true,write:false,format:'esm',platform:'node'});
const {newGame} = await import('data:text/javascript;base64,'+Buffer.from(bundled.outputFiles[0].text).toString('base64'));
const browser = await chromium.launch({executablePath:process.env.CHROME_PATH || '/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const base=process.env.BASE_URL || 'http://localhost:5173';
try {
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const s=newGame(2609); s.player.y=s.world.samples[0].y;
 await page.addInitScript(state=>{if(!localStorage.getItem('kreatbio.microload.save'))localStorage.setItem('kreatbio.microload.save',JSON.stringify({version:3,state}));},s);
 await page.goto(base);await page.getByRole('button',{name:'Continue culture'}).click();
 const read=()=>page.evaluate(()=>{window.dispatchEvent(new Event('pagehide'));return JSON.parse(localStorage.getItem('kreatbio.microload.save')).state;});
 await page.keyboard.press('e');await page.getByText('Why examine this soil?').waitFor();
 assert.match(await page.locator('#overlay').innerText(),/What do you get/);
 await page.waitForTimeout(2200);assert.equal((await read()).scans.length,0);
 await page.getByRole('button',{name:'Examine this soil’s DNA'}).click();
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 await page.waitForTimeout(300);assert.equal(await page.getByRole('dialog',{name:'scanning',exact:true}).isVisible(),true);
 await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
 const scanning=await read();await page.waitForTimeout(400);const midway=await read();
 assert.deepEqual(midway.player,scanning.player);assert.equal(midway.elapsed,scanning.elapsed);
 await page.getByRole('button',{name:'Close soil sample'}).click();assert.equal((await read()).scans.length,0);
 await page.keyboard.press('e');await page.getByRole('button',{name:'Examine this soil’s DNA'}).click();await page.getByRole('dialog',{name:'scan-result',exact:true}).waitFor();
 assert.deepEqual((await read()).scans,['root-partner']);
 assert.match(await page.locator('#overlay').innerText(),/Rhizobium/);
 await page.locator('#overlay').click({position:{x:4,y:4}});
 await page.locator('.scan-explanation h3').first().click();
 await page.keyboard.press('Escape');await page.keyboard.press('Enter');await page.keyboard.press('Space');
 assert.equal(await page.getByRole('dialog',{name:'scan-result',exact:true}).isVisible(),true);
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 assert.equal(await page.getByRole('dialog',{name:'scan-result',exact:true}).isVisible(),true);
 await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
 assert.match(await page.locator('#overlay').innerText(),/highlighted N/);
 const result=await read();await page.keyboard.down('s');await page.waitForTimeout(2500);await page.keyboard.up('s');
 assert.deepEqual((await read()).player,result.player);assert.equal((await read()).elapsed,result.elapsed);
 await page.getByRole('button',{name:'More in Field Journal'}).click();await page.getByRole('button',{name:'Back to soil result'}).click();
 await page.screenshot({path:'test-results/soil-result.png',fullPage:true});
 await page.getByRole('button',{name:'Close soil sample'}).click();
 await page.keyboard.press('e');await page.getByRole('dialog',{name:'scan-result',exact:true}).waitFor();assert.equal((await read()).scans.length,1);
 await page.getByRole('button',{name:'Close soil sample'}).click();
 await page.screenshot({path:'test-results/sequenced-patch.png',fullPage:true});
 await page.locator('#journal').click();const before=await read();
 assert.match(await page.locator('#overlay').innerText(),/Compatible|compatible/);
 assert.match(await page.locator('#overlay').innerText(),/other bacteria and fungi/);
 await page.keyboard.down('s');await page.waitForTimeout(250);await page.keyboard.up('s');
 assert.deepEqual((await read()).player,before.player);assert.equal((await read()).elapsed,before.elapsed);
 await page.screenshot({path:'test-results/journal.png',fullPage:true});
 await page.keyboard.press('Escape');assert.equal(await page.locator('#overlay').isHidden(),true);
 await page.keyboard.press('Escape');await page.locator('#journal').click();
 await page.getByRole('button',{name:'Back to pause menu'}).click();assert.match(await page.locator('#overlay').innerText(),/little breather/);
 await page.reload();await page.getByRole('button',{name:'Continue culture'}).click();assert.deepEqual((await read()).scans,['root-partner']);
 await page.keyboard.press('Escape');await page.locator('#journal').click();await page.getByRole('button',{name:'Back to pause menu'}).click();await page.getByRole('button',{name:'Start a new culture'}).click();await page.getByRole('button',{name:'Replace save & start new'}).click();assert.deepEqual((await read()).scans,[]);await page.getByRole('button',{name:'Let’s dig'}).click();
 await page.setViewportSize({width:390,height:844});await page.locator('#journal').click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'test-results/journal-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('Discovery browser tests passed: scan pause/cancel/completion, findings, journal modes, reload and narrow layout.');
} finally {await browser.close();}
